### ISSUE TITLE
Fatal error in vanilla: Mono version not properly updated?

### ISSUE THREAD

**Issue by jonjonjapon** [ryansheehan/terraria#104]
Hey all. I'm very much a scrub at this kind of thing but I'm thinking what I'm seeing is an issue on the Dockerfile side.
Saw that the mono version was updated, but I'm seeing an error that "Your mono runtime and class libraries are out of sync." in the log when trying to boot the container in the most recent version. Any thoughts/help?

Attaching logfile below:

[ryshe-terraria.csv](https://github.com/ryansheehan/terraria/files/8338518/ryshe-terraria.csv)

**Comment by Gameaday** [comment]
Hello I also have been experiencing the vanilla issue.
I built a docker image with every single version of full/slim mono since the last known working version and found that the Vanilla docker image fails starting 6.12.0.117, regardless of slim or not. As such I recommend TSHOCK use the current 6.12.0.122-slim since it's known to work fine. and **VANILLA should use 6.10.0.104-slim** as that is the last good version of mono for that build. @ryansheehan Thank you for your great work on the docker image, sorry for the typo in my last submission. I didn't catch the change upstream in the url and didn't have a pipeline setup to confirm build. 

I can provide a patch if necessary

**Comment by ryansheehan** [comment]
thanks for the updates.  I updated the containers to use the versions you recommended.  I need a way to unit test these versions.  I rely on the community for feedback!   Thank you @Gameaday

**Comment by Gameaday** [comment]
No problems at all! Glad to help where I can. also - I did run mobile and it seems to work fine. it's still on the newest -slim mono so no changes needed there.

**Comment by Gameaday** [comment]
@jonjonjapon can you confirm the latest image (live) fixes your issue?

**Comment by jonjonjapon** [comment]
@Gameaday Hey, vanilla is up and running, many thanks to both of you.
Wonder what changed with mono to break this?
