### ISSUE TITLE
Terraria 1.4 support

### ISSUE THREAD

**Issue by yoruvo** [ryansheehan/terraria#28]
Hey,

from what I'm seeing, Terraria website already allows downloading the server for 1.4 (Journey's End update):

https://terraria.org/system/dedicated_servers/archives/000/000/035/original/terraria-server-1401.zip?1589643840

Does anything need to be done from your side to adapt this image to 1.4, or is it something I can do manually as well?

**Comment by gregflynn** [comment]
Looks like to completely work, a TShock release to support 1.4 is needed, according to their twitter they're working on that now.

**Comment by ryansheehan** [comment]
I am anxiously awaiting the update from the tshock guys.
https://github.com/Pryaxis/TShock/releases

When they update, I can update the container.

**Comment by Selbi182** [comment]
Prerelease 1 is out: https://github.com/Pryaxis/TShock/releases/tag/v4.4.0-pre1

Will you update the container with it already or will you wait for the full release?

**Comment by ryansheehan** [comment]
I'll work on a dev build and see where things wind up.

**Comment by ryansheehan** [comment]
I just posted a new container with the pre-release build.  Plugins may not
work, but tested locally and things loaded.

**Comment by Selbi182** [comment]
That was wicked fast,t hank you! I'll pull the new container and will report back soon. We want a vanilla experience anyway, so plugins are no deal breaker.

**Comment by Selbi182** [comment]
Alright, got it to work. I'm not sure why, but the world select (1, 2, 3, n, d) doesn't seem to work. Maybe I configurated the Docker wrong, but I was only able to launch a world using the -world param.

In any case, the base game itself seems to run fine now! 👍

**Comment by ryansheehan** [comment]
the docker run command needs a -it flag set

**Comment by Selbi182** [comment]
The flags are set, still no world selection.

But I need to take back what I said in my last post, it doesn't work after all. My friends and I (four in total) were playing for about ten minutes before we all had our Terraria.exe crash for us, almost simultaneously. Freeze frame, process had to be killed.

No idea if this is because of TShock or the container.

**Comment by ryansheehan** [comment]
Probably TShock.  I'll be working on it some more after work today.

**Comment by ryansheehan** [comment]
I just did a republish of the container with a new bootstrap script to copy the TShockAPI.dll into the plugins folder, could you retry and let me know how it goes?

**Comment by Selbi182** [comment]
Pulled. Can't really give much feedback yet, we usually start our gaming sessions in the evening. It didn't crash for me solo within the first half our yet though, which seems to be an improvement.

I'll report back in the evening when our group is assembled again. :)

Unfortunately, the world selection is still not working, which doesn't really make any sense because using `docker exec ls -l /world` I can clearly see that the world files have been copied over to the container successfully and the -world still works, as mentioned previously. I suppose this might be an issue with Terraria Server though.

**Comment by Selbi182** [comment]
I wish I could give you more info than this, but yesterday was absolutely chaotic.

Long story short, the game ran worse than before and a few things quickly became a meme. For example, every time someone died they weren't able to open chests anymore and had to re-log to the server. The Wall of Flesh was standing still for a solid minute, after which it lightspeeded halfway across the map, killing all of us. Dropped items would randomly disappear; we gave up picking back up our cash every time we died very soon.

All this while I had an eye on the server load and never saw it go above maybe 70% total CPU usage; RAM and network load were also reasonable.

The big question is whether this is related to TShock's prerelease, your Dockerfile, or our own Docker environment on the server. Seeing how the latter one is really the only one we have power to control, we have decided to go back to hosting a vanilla server outside of Docker (still on the same physical server though). Things look stable so far.

It's probably not helpful to you at all, but perhaps you can make something out of it. If you need more information, shout it out.

**Comment by ryansheehan** [comment]
These would all be issues with TShock.  For lack of a better example,
docker is like the is operating system.  It's not going to change how the
software is run.  We're you playing on preview 3?

I plan on my first gaming group tonight, so I'll get to see first hand how
it goes.

**Comment by Selbi182** [comment]
Pre2, we were honestly too tired of potentially having to deal with yet another unstable gaming night. I could probably try to set up a TShock server _outside_ of our Docker environment, just to see if it eliminates that uncertainty. No idea if I can convince my people to be guinea pigs again though.

Also, going slightly off-topic here: Have you considered doing a variation of this Dockerfile that uses the [vanilla Terraria server](https://terraria.gamepedia.com/Server#How_to_.28Linux.29)? Truth to be told, I discovered your project because I was looking for an out-of-the-box solution without having to fiddle around with server settings too much (oh the irony). TShock is overkill for small private groups and I feel like I'm not the only one who would appreciate a simple solution that just works.

**Comment by scotws** [comment]
I'd second @Selbi182's idea of a container that uses the simple vanilla server. Never heard of TShock before (I play Terraria with my kids mainly, sorry) and have never used the advanced features.

**Comment by ryansheehan** [comment]
I like the idea of this, but I'll have look into this when the dust settles around TShock.  This would be a decent change to how the dockerfile is setup.  We would need to change the build stage to pull the server executable from steam, and I am not sure off hand what all that would take.

**Comment by seevee** [comment]
Just poked around for a bit - it looks like it might be possible to download the server binary straight from terraria.org: https://github.com/kaysond/docker-terraria/blob/6f237a70221c1e1a90be302154801cddd69354ca/Dockerfile#L7

**Comment by ryansheehan** [comment]
I wanted to let you guys know that I published a version of the container built on the vanilla server.  I havent had the chance to document it but you can do a `docker pull ryshe/terraria:vanilla-1.4.0.5` if you want to check it out.  One thing I did notice is that you *have to* run the container with the `-it` flag or it will crash.  Server commands must be typed into the terminal.  Another pain point with vanilla is that it does not auto save when all players exit.  If you want to force a save then you have type `save` into the cli of the terminal running the server.

I tried out the container last night, and it seems to work okay.  The volume point for save files is the same as tshock.  I reused my world generated with the tshock version without any additional issue.  You can also generate a world when you run without any flags.

```
docker run -it --rm -p 7777:7777 --name=terraria -v <path to dir with world file>:/root/.local/share/Terraria/Worlds ryshe/terraria:vanilla-1.4.0.5
```

and to load directly into a save file

```
docker run -it --rm -p 7777:7777 --name=terraria -v <path to dir with world file>:/root/.local/share/Terraria/Worlds ryshe/terraria:vanilla-1.4.0.5 -world /root/.local/share/Terraria/Worlds/<you save file>.wld
```

If you don't want to keep the terminal open, but also dont want to exit the terraria server you can press `ctrl+p` + `ctrl+q` in the terminal window to push the session into the background.  Then it is safe to close the terminal window.  If you want to resume the terminal session later, from your terminal type `docker attach terrraria`
