### ISSUE TITLE
TShock 4.4.0 Pre-release 11 for Terraria 1.4.0.5

### ISSUE THREAD

**Issue by skelterjohn** [ryansheehan/terraria#48]
Anything I can do to help? :) Last time I tried to roll my own image (starting with your 1.3 Dockerfile), I screwed up world persistence, so I've been reluctant to try again.

But you're likely a busy person who doesn't spend every day working on terraria server container images - happy to help if you give me some pointers (I work professionally with docker et al, no starting points needed for that).

**Comment by ryansheehan** [comment]
I should make a todo list.  I wish I had more time to throw at this stuff!  It's funny because this Terraria/TShock container was my foray into learning docker.  It was the very first container I ever built; about 7 years ago now.    

Contributions are awesome.  If I had more time there are a couple things I would tackle:

1. I'm not sure how I would do it, but I would love to setup Github Actions to query the tshock releases and automatically update the Dockerfile.  It might behoove me to move the docker build into github actions.  Currently I have it setup to automate from the dockerhub side of things.  Dockerhub has a webhook it automatically setup into github to kick off builds when new commits come in.

2. The TShock guys removed `-worldpath` for a bit.  It threw the container into disarray and forced me to use some long volume path maps.  In pre-release 9 they added `-worldselectpath` which is similar to the old worldpath flag.  I haven't had a lot of time to mess with it, but when I did I kept getting into an infinite loop on startup.  

3. I have gotten several requests to containerize the regular terraria server.  It might be nice to have a separate Dockerfile that I can also build and tag for people that want just that.

**Comment by skelterjohn** [comment]
re: vanilla. i suggest you host two images from this repo: ryshe/tshock (current one) and ryshe/terraria (vanilla).

To avoid massive confusion you'd probably have to stop using a 'latest' tag, but I think that's ok because people always need to be explicit about which version the server and client are talking to. Or, branch it to ryshe/terraria-tshock and ryshe/terraria-vanilla, which would be very clear.

Definitely do *not* have ryshe/terraria:tshock and ryshe/terraria:vanilla or anything along those lines.

**Comment by skelterjohn** [comment]
re: automatic updates, I see a lot potentially going wrong there :) for instance, if you had that in place you would have distributed broken images when they removed `-worldpath`. I don't think it's a good idea unless you can have some fairly robust automated testing, and I don't think that would save you any time.

**Comment by skelterjohn** [comment]
I'll try to find some time to experiment with `-worldselectpath`.

**Comment by ryansheehan** [comment]
I agree with the explicit versions.  We have that rule at work too.  Part of `:latest` being used, still, to this day is just because a lot of people using the container don't understand how docker works and are just looking for an easy button to spin up a terraria server without having to learn much.

You're probably right about breaking changes.  I am hoping that once the dust settles around the pre-release there wont be too much more of cli parameters breaking.  With that said the automated testing would be hard to validate in the event of infinite loops etc.

**Comment by skelterjohn** [comment]
So, I built a container from a fresh clone of this repo, and it worked just fine.

`$ docker run -it -p 7777:7777 -v $PWD:/root/.local/share/Terraria/Worlds tshock`

Running it from the directory I want to persist worlds to.

Maybe this is ready to go? :)

**Comment by skelterjohn** [comment]
And, "worked just fine" includes me connecting from my 1.4.0.5 client in steam to a 127.0.0.1:7777 server.
