### ISSUE TITLE
Admin Accounts

### ISSUE THREAD

**Issue by stummyhurt** [ryansheehan/terraria#51]
I'm trying to change permissions and I don't have access to the necessary commands. Is there an admin account already made that I can login to or can I redo the setup somehow? I've tried deleting the tshock.sqlite file to redo setup to no avail.

**Comment by ryansheehan** [comment]
This is really a tshock question, not sure if they have anything on that
github <https://github.com/Pryaxis/TShock/discussions>, but it's
worth a look.  I believe you can use a sqlite editor and find the table for
the user and update the password.  I only know this because I had the same
problem.  I actually think my account was not a superuser account too.
Passwords are stored in plain text in the sqlite file.
